name: CI
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10, 12]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: ls modules/*/package.json | xargs -n1 md5sum > deps.txt
      - name: Use Yarn@1.21.1
        # https://yarnpkg.com/ja/docs/install#linux-tab
        run: |
          sudo unlink $(which yarn)
          curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
          echo ::set-env name=PATH::$(echo $HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH)
      - name: Display version of Node.js, npm, Yarn
        run: |
          node -v
          npm -v
          yarn --version

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('deps.txt') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn
      - run: yarn lint

  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10, 12]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: ls modules/*/package.json | xargs -n1 md5sum > deps.txt
      - name: Use Yarn@1.21.1
        # https://yarnpkg.com/ja/docs/install#linux-tab
        run: |
          sudo unlink $(which yarn)
          curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
          echo ::set-env name=PATH::$(echo $HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH)
      - name: Display version of Node.js, npm, Yarn
        run: |
          node -v
          npm -v
          yarn --version

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('deps.txt') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn
      - run: yarn type-check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10, 12]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo apt-get install mongodb-clients
      - run: ls modules/*/package.json | xargs -n1 md5sum > deps.txt
      - name: Use Yarn@1.21.1
        # https://yarnpkg.com/ja/docs/install#linux-tab
        run: |
          sudo unlink $(which yarn)
          curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
          echo ::set-env name=PATH::$(echo $HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH)

      - name: Display version of Node.js, npm, Yarn
        run: |
          node -v
          npm -v
          yarn --version

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('deps.txt') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn
      - run: yarn cov-test
      - run: npx lcov-result-merger 'modules/*/coverage/lcov.info' | npx coveralls
        env:
          COVERALLS_GIT_BRANCH: "${{ github.ref }}"
